name: CI / CD pipeline feature branches

on:
  push:
    branches-ignore:
      - master

jobs:
  e2e:
    runs-on: ubuntu-20.04
    environment: local
    strategy:
      matrix:
        node-version: [22.x]
        mongodb-version: ['7.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: 'Use Node.js ${{ matrix.node-version }}'
      uses: actions/setup-node@v3
      with:
        node-version: '${{ matrix.node-version }}'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '${{ matrix.mongodb-version }}'

    - run: npm install

    - run: chmod +x ./cypress/utils/clear_db.sh

    - run: chmod +x ./cypress/utils/seed_db.sh

    - name: Cypress
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        build: npm run build
        start: npm start
        wait-on: 'http://localhost:3000'
        env: true
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_LEADERBOARD_DB: ${{ secrets.MONGODB_LEADERBOARD_DB }}
        MONGODB_MINESWEEPER_COLLECTION: ${{ secrets.MONGODB_MINESWEEPER_COLLECTION }}
        CRON_SECRET: ${{ secrets.CRON_SECRET }}

